### ISSUE TITLE
Error: Access violation

### ISSUE THREAD

**Issue by Razva** [linuxserver/docker-doublecommander#5] opened 2021-08-13 14:35 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Guacamole -> DoubleCommander should work as expected, with no errors showing on access.

## Current Behavior
When accessing DoubleCommander we're greeted with an error stating *Error: Access violation*. Here's a screenshot: https://www.screencast.com/t/8JxlCLXs

## Steps to Reproduce
Start DoubleCommander via CLI or via Docker-Compose. Access the app via browser.

## Environment
**OS:** Debian 10
**CPU architecture:** arm64
**How docker service was installed:** From the distro's repo.
**Device:** Odroid HC4
**Extra OS info:**
- Linux version 5.11.0-odroid-arm64 (gcc-8 (Debian 8.3.0-6) 8.3.0, GNU ld (GNU Binutils for Debian) 2.31.1)  SMP PREEMPT Debian 5.11.18-202108050550~buster (2021-08-04)
- Docker version 18.09.1, build 4c52b90

## Command used to create docker container (run/create/compose/screenshot)
Using `docker-compose.yml`:

```
version: "2.1"
services:
  doublecommander:
    image: ghcr.io/linuxserver/doublecommander
    container_name: doublecommander
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /home/razvanr/doublecommander:/config
      - /home/razvanr:/data
    ports:
      - 8086:3000
    restart: unless-stopped
```

## Docker logs
Logfile here: http://sprunge.us/Rcye2Z

## Permissions
```
# ls -la /home/razvanr/
drwxr-xr-x 8 razvanr razvanr 4096 Aug 13 17:20 doublecommander

# ls -la /home/razvanr/doublecommander/
total 56
drwxr-xr-x 8 razvanr razvanr  4096 Aug 13 17:20 .
drwxr-xr-x 5 razvanr razvanr  4096 Aug 13 17:19 ..
-rw-r--r-- 1 razvanr razvanr  2408 Aug 13 17:19 .bashrc
drwxrwxr-x 3 razvanr razvanr  4096 Aug 13 17:20 .cache
drwxr-xr-x 5 razvanr razvanr  4096 Aug 13 17:20 .config
drwx------ 3 razvanr razvanr  4096 Aug 13 17:20 .dbus
drwx------ 3 razvanr razvanr  4096 Aug 13 17:20 .local
-rw-r--r-- 1 razvanr razvanr 13347 Aug 13 17:20 .xorgxrdp.10.log
drwxr-xr-x 2 root    root     4096 Aug 13 17:19 custom-cont-init.d
drwxr-xr-x 2 root    root     4096 Aug 13 17:19 custom-services.d
-rwxr-xr-x 1 razvanr razvanr    82 Aug 13 17:19 startwm.sh
```

**Comment by mrp-yt** [comment] 2021-10-15 22:21
Same here.
Different setup with same docker image 

Linux galaxy 5.10.63-v8+ #1457 SMP PREEMPT Tue Sep 28 11:27:02 BST 2021 aarch64 GNU/Linux
RPi4 8GM Ram
DietPi OS

**Comment by spewu** [comment] 2021-12-14 08:46
Looks like it should be fixed in v. 0.8.4: https://doublecmd.sourceforge.io/mantisbt/view.php?id=2126

So hope linuxserver will update the docker image :)

**Comment by aptalca** [comment] 2021-12-14 13:13
Our updates are automated. When there is a new version in the repo, we'll push out a new build

**Comment by spewu** [comment] 2021-12-14 14:07
> Our updates are automated. When there is a new version in the repo, we'll push out a new build

Ahh, nice!

So, I might be missing something, but it looks like they released v. 1.0.2 3 days ago, and have done many newer releases than v. 0.8.2 that is in this image. So is there some problem in the way you detect new versions?

https://sourceforge.net/p/doublecmd/wiki/Download/

**Comment by aptalca** [comment] 2021-12-14 14:20
We install from the ubuntu repo: https://github.com/linuxserver/docker-doublecommander/blob/master/Dockerfile#L14

**Comment by spewu** [comment] 2021-12-14 14:28
> We install from the ubuntu repo: https://github.com/linuxserver/docker-doublecommander/blob/master/Dockerfile#L14

Ok, so I guess it should be v. 0.9.10: https://packages.ubuntu.com/impish/doublecmd-gtk ?

I just installed the latest linuxserver docker image, and I get v. 0.8.2:
![image](https://user-images.githubusercontent.com/1662016/146017181-38861a79-0ad8-4c5e-8cfa-b494df53b767.png)

**Comment by spewu** [comment] 2021-12-14 14:30
Ahh ... it is probably because it is on `ubuntu bionic`: https://packages.ubuntu.com/bionic/doublecmd-gtk

**Comment by aptalca** [comment] 2021-12-14 14:30
right, we can update to focal, which will go up a little further but it will still be behind the latest

**Comment by spewu** [comment] 2021-12-14 14:32
> right, we can update to focal, which will go up a little further but it will still be behind the latest

I think this exact bug was fixed in 0.8.4 - and focal will give us 0.9.8 ... so that should be enough 🤞

**Closed as completed** 2021-12-14 16:11 UTC
Labels: no-issue-activity

**Comment by spewu** [comment] 2021-12-14 18:04
@aptalca thanks a lot!

**Comment by mrp-yt** [comment] 2021-12-14 20:20
I can confirm too. 
Working perfectly withy setup.
